Server:
  Port: 8901
  ReadTimeout: 15s
  WriteTimeout: 15s

API:
  BasePath: ""
  APITimeout: 15s
  EnableSwagger: true

Database:
  SlaveDSN: "postgres://postgres:1235813@localhost:5433/elections?sslmode=disable"
  MasterDSN: "postgres://postgres:1235813@localhost:5433/elections?sslmode=disable"
  RetryInterval: 10
  MaxIdleConn: 10
  MaxConn: 10
  ConnMaxLifetime: 10s

Kafka:
  Producer:
    Brokers:
      - localhost:9092
    MaxAttempt: 5
    Idempotent: true
  Topics:
    MasterDataElection:
      Value: "election.masterdata-election"
      ErrorHandler: "Phase1"
      WithBackOff: true
    MasterDataParty:
      Value: "election.masterdata-party"
      ErrorHandler: "Phase1"
      WithBackOff: true
    MasterDataSupportingParty:
      Value: "election.masterdata-supporting-party"
      ErrorHandler: "Phase1"
      WithBackOff: true

JWT:
  Secret: "^87adb2&91hnGaWd7"

GrpcServer:
  Port: 35000

Encryption:
  Key : "NZkrqmVGg6Bi4QbqGXbH9wz3Q0+NCGvMKA2j8hqD5eM="

BlockchainConfig:
  GanacheURL: "http://127.0.0.1:7545"
  VotechainAddress: "0x49e158C527736f447A400BDFB128aEb3F0390b88"
  ElectionManagerAddress: "0x6957Afa20F78cd0556D57b5Ca5506d0B2C815402"
  KPUManagerAddress: "0x75E0A085E5839c9a53DF19d658F431B1D1e2D8F9"
  VoterManagerAddress: "0x7B6B56B22efEA4142A1135c3628110Bb1546f012"
  VotechainBaseAddress: "0x57a719B3166F818798135Abc81C87a9A2697A4c9"


Cors:
  AllowOrigins: "*"
  AllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
  AllowHeaders: "Content-Type,Authorization"
  AllowCredentials: false
  ExposeHeaders: "X-Custom-Header"
  MaxAge: 3600