// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/election/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ElectionRepository is an autogenerated mock type for the ElectionRepository type
type ElectionRepository struct {
	mock.Mock
}

// ActivateElectionPair provides a mock function with given fields: ctx, id
func (_m *ElectionRepository) ActivateElectionPair(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ActivateElectionPair")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllElectionPairs provides a mock function with given fields: ctx
func (_m *ElectionRepository) GetAllElectionPairs(ctx context.Context) ([]model.ElectionPair, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllElectionPairs")
	}

	var r0 []model.ElectionPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.ElectionPair, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.ElectionPair); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ElectionPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionPairByID provides a mock function with given fields: ctx, id
func (_m *ElectionRepository) GetElectionPairByID(ctx context.Context, id uuid.UUID) (*model.ElectionPair, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionPairByID")
	}

	var r0 *model.ElectionPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.ElectionPair, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.ElectionPair); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ElectionPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionPairByNo provides a mock function with given fields: ctx, no
func (_m *ElectionRepository) GetElectionPairByNo(ctx context.Context, no string) (*model.ElectionPair, error) {
	ret := _m.Called(ctx, no)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionPairByNo")
	}

	var r0 *model.ElectionPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.ElectionPair, error)); ok {
		return rf(ctx, no)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.ElectionPair); ok {
		r0 = rf(ctx, no)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ElectionPair)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, no)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPairDetailByPairID provides a mock function with given fields: ctx, pairID
func (_m *ElectionRepository) GetPairDetailByPairID(ctx context.Context, pairID uuid.UUID) (*model.PairDetail, error) {
	ret := _m.Called(ctx, pairID)

	if len(ret) == 0 {
		panic("no return value specified for GetPairDetailByPairID")
	}

	var r0 *model.PairDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.PairDetail, error)); ok {
		return rf(ctx, pairID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.PairDetail); ok {
		r0 = rf(ctx, pairID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PairDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pairID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertElectionPair provides a mock function with given fields: ctx, pair
func (_m *ElectionRepository) InsertElectionPair(ctx context.Context, pair *model.ElectionPair) error {
	ret := _m.Called(ctx, pair)

	if len(ret) == 0 {
		panic("no return value specified for InsertElectionPair")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ElectionPair) error); ok {
		r0 = rf(ctx, pair)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendTxToBlockchain provides a mock function with given fields: ctx, signedTransaction
func (_m *ElectionRepository) SendTxToBlockchain(ctx context.Context, signedTransaction string) (string, error) {
	ret := _m.Called(ctx, signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for SendTxToBlockchain")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, signedTransaction)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, signedTransaction)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, signedTransaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateElectionPairPhoto provides a mock function with given fields: ctx, id, photoPath
func (_m *ElectionRepository) UpdateElectionPairPhoto(ctx context.Context, id uuid.UUID, photoPath string) error {
	ret := _m.Called(ctx, id, photoPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateElectionPairPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, photoPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePresidentPhoto provides a mock function with given fields: ctx, id, photoPath
func (_m *ElectionRepository) UpdatePresidentPhoto(ctx context.Context, id uuid.UUID, photoPath string) error {
	ret := _m.Called(ctx, id, photoPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePresidentPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, photoPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateVicePresidentPhoto provides a mock function with given fields: ctx, id, photoPath
func (_m *ElectionRepository) UpdateVicePresidentPhoto(ctx context.Context, id uuid.UUID, photoPath string) error {
	ret := _m.Called(ctx, id, photoPath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVicePresidentPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, photoPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertPairDetail provides a mock function with given fields: ctx, detail
func (_m *ElectionRepository) UpsertPairDetail(ctx context.Context, detail *model.PairDetail) error {
	ret := _m.Called(ctx, detail)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPairDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PairDetail) error); ok {
		r0 = rf(ctx, detail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewElectionRepository creates a new instance of ElectionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElectionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElectionRepository {
	mock := &ElectionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
