// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/election/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PartyRepository is an autogenerated mock type for the PartyRepository type
type PartyRepository struct {
	mock.Mock
}

// DeleteParty provides a mock function with given fields: ctx, id
func (_m *PartyRepository) DeleteParty(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllParties provides a mock function with given fields: ctx
func (_m *PartyRepository) GetAllParties(ctx context.Context) ([]model.Party, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllParties")
	}

	var r0 []model.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Party, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Party); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyByID provides a mock function with given fields: ctx, id
func (_m *PartyRepository) GetPartyByID(ctx context.Context, id uuid.UUID) (*model.Party, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyByID")
	}

	var r0 *model.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Party, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Party); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertParty provides a mock function with given fields: ctx, party
func (_m *PartyRepository) InsertParty(ctx context.Context, party *model.Party) error {
	ret := _m.Called(ctx, party)

	if len(ret) == 0 {
		panic("no return value specified for InsertParty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Party) error); ok {
		r0 = rf(ctx, party)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateParty provides a mock function with given fields: ctx, party
func (_m *PartyRepository) UpdateParty(ctx context.Context, party *model.Party) (*model.Party, error) {
	ret := _m.Called(ctx, party)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParty")
	}

	var r0 *model.Party
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Party) (*model.Party, error)); ok {
		return rf(ctx, party)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Party) *model.Party); ok {
		r0 = rf(ctx, party)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Party)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Party) error); ok {
		r1 = rf(ctx, party)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPartyRepository creates a new instance of PartyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartyRepository {
	mock := &PartyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
