// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_repository

import (
	context "context"

	model "github.com/nocturna-ta/election/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SupportingPartyRepository is an autogenerated mock type for the SupportingPartyRepository type
type SupportingPartyRepository struct {
	mock.Mock
}

// AddSupportingParty provides a mock function with given fields: ctx, supportingParty
func (_m *SupportingPartyRepository) AddSupportingParty(ctx context.Context, supportingParty *model.SupportingParty) error {
	ret := _m.Called(ctx, supportingParty)

	if len(ret) == 0 {
		panic("no return value specified for AddSupportingParty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SupportingParty) error); ok {
		r0 = rf(ctx, supportingParty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSupportingPartiesByPairID provides a mock function with given fields: ctx, pairID
func (_m *SupportingPartyRepository) GetSupportingPartiesByPairID(ctx context.Context, pairID uuid.UUID) ([]model.SupportingParty, error) {
	ret := _m.Called(ctx, pairID)

	if len(ret) == 0 {
		panic("no return value specified for GetSupportingPartiesByPairID")
	}

	var r0 []model.SupportingParty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.SupportingParty, error)); ok {
		return rf(ctx, pairID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.SupportingParty); ok {
		r0 = rf(ctx, pairID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SupportingParty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pairID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveSupportingParty provides a mock function with given fields: ctx, pairID, partyID
func (_m *SupportingPartyRepository) RemoveSupportingParty(ctx context.Context, pairID uuid.UUID, partyID uuid.UUID) error {
	ret := _m.Called(ctx, pairID, partyID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSupportingParty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, pairID, partyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSupportingPartyRepository creates a new instance of SupportingPartyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupportingPartyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupportingPartyRepository {
	mock := &SupportingPartyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
