// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	http "github.com/nocturna-ta/golib/http"
	mock "github.com/stretchr/testify/mock"

	request "github.com/nocturna-ta/election/internal/usecases/request"

	response "github.com/nocturna-ta/election/internal/usecases/response"

	uuid "github.com/google/uuid"
)

// ElectionUseCases is an autogenerated mock type for the ElectionUseCases type
type ElectionUseCases struct {
	mock.Mock
}

// ActivateElectionPair provides a mock function with given fields: ctx, req
func (_m *ElectionUseCases) ActivateElectionPair(ctx context.Context, req *request.ElectionPairActivationRequest) (*response.ElectionPairActivationResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ActivateElectionPair")
	}

	var r0 *response.ElectionPairActivationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ElectionPairActivationRequest) (*response.ElectionPairActivationResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ElectionPairActivationRequest) *response.ElectionPairActivationResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionPairActivationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ElectionPairActivationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllElectionPairs provides a mock function with given fields: ctx
func (_m *ElectionUseCases) GetAllElectionPairs(ctx context.Context) (*response.ElectionPairListResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllElectionPairs")
	}

	var r0 *response.ElectionPairListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*response.ElectionPairListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *response.ElectionPairListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionPairListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionPairByID provides a mock function with given fields: ctx, id
func (_m *ElectionUseCases) GetElectionPairByID(ctx context.Context, id uuid.UUID) (*response.ElectionPairResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionPairByID")
	}

	var r0 *response.ElectionPairResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.ElectionPairResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.ElectionPairResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionPairResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionPairByNo provides a mock function with given fields: ctx, no
func (_m *ElectionUseCases) GetElectionPairByNo(ctx context.Context, no string) (*response.ElectionPairResponse, error) {
	ret := _m.Called(ctx, no)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionPairByNo")
	}

	var r0 *response.ElectionPairResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.ElectionPairResponse, error)); ok {
		return rf(ctx, no)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.ElectionPairResponse); ok {
		r0 = rf(ctx, no)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionPairResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, no)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionPairDetail provides a mock function with given fields: ctx, pairID
func (_m *ElectionUseCases) GetElectionPairDetail(ctx context.Context, pairID uuid.UUID) (*response.ElectionPairDetailResponse, error) {
	ret := _m.Called(ctx, pairID)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionPairDetail")
	}

	var r0 *response.ElectionPairDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.ElectionPairDetailResponse, error)); ok {
		return rf(ctx, pairID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.ElectionPairDetailResponse); ok {
		r0 = rf(ctx, pairID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionPairDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pairID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionPairFull provides a mock function with given fields: ctx, id
func (_m *ElectionUseCases) GetElectionPairFull(ctx context.Context, id uuid.UUID) (*response.ElectionPairFullResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionPairFull")
	}

	var r0 *response.ElectionPairFullResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.ElectionPairFullResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.ElectionPairFullResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionPairFullResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetElectionPairPhoto provides a mock function with given fields: ctx, id
func (_m *ElectionUseCases) GetElectionPairPhoto(ctx context.Context, id uuid.UUID) (*http.File, string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetElectionPairPhoto")
	}

	var r0 *http.File
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*http.File, string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *http.File); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) string); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetPresidentPhoto provides a mock function with given fields: ctx, id
func (_m *ElectionUseCases) GetPresidentPhoto(ctx context.Context, id uuid.UUID) (*http.File, string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPresidentPhoto")
	}

	var r0 *http.File
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*http.File, string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *http.File); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) string); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetVicePresidentPhoto provides a mock function with given fields: ctx, id
func (_m *ElectionUseCases) GetVicePresidentPhoto(ctx context.Context, id uuid.UUID) (*http.File, string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVicePresidentPhoto")
	}

	var r0 *http.File
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*http.File, string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *http.File); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) string); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterElectionPair provides a mock function with given fields: ctx, req
func (_m *ElectionUseCases) RegisterElectionPair(ctx context.Context, req *request.ElectionPairRegistrationRequest) (*response.ElectionPairResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterElectionPair")
	}

	var r0 *response.ElectionPairResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ElectionPairRegistrationRequest) (*response.ElectionPairResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ElectionPairRegistrationRequest) *response.ElectionPairResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionPairResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ElectionPairRegistrationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertElectionPairDetail provides a mock function with given fields: ctx, req
func (_m *ElectionUseCases) UpsertElectionPairDetail(ctx context.Context, req *request.ElectionPairDetailRequest) (*response.ElectionPairDetailResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpsertElectionPairDetail")
	}

	var r0 *response.ElectionPairDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.ElectionPairDetailRequest) (*response.ElectionPairDetailResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.ElectionPairDetailRequest) *response.ElectionPairDetailResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.ElectionPairDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.ElectionPairDetailRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewElectionUseCases creates a new instance of ElectionUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElectionUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElectionUseCases {
	mock := &ElectionUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
