// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	http "github.com/nocturna-ta/golib/http"
	mock "github.com/stretchr/testify/mock"

	request "github.com/nocturna-ta/election/internal/usecases/request"

	response "github.com/nocturna-ta/election/internal/usecases/response"

	uuid "github.com/google/uuid"
)

// PartyUseCases is an autogenerated mock type for the PartyUseCases type
type PartyUseCases struct {
	mock.Mock
}

// DeleteParty provides a mock function with given fields: ctx, id
func (_m *PartyUseCases) DeleteParty(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllParties provides a mock function with given fields: ctx
func (_m *PartyUseCases) GetAllParties(ctx context.Context) ([]response.PartyResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllParties")
	}

	var r0 []response.PartyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]response.PartyResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []response.PartyResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.PartyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyByID provides a mock function with given fields: ctx, id
func (_m *PartyUseCases) GetPartyByID(ctx context.Context, id string) (*response.PartyResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyByID")
	}

	var r0 *response.PartyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*response.PartyResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *response.PartyResponse); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PartyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPartyPhoto provides a mock function with given fields: ctx, id
func (_m *PartyUseCases) GetPartyPhoto(ctx context.Context, id uuid.UUID) (*http.File, string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPartyPhoto")
	}

	var r0 *http.File
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*http.File, string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *http.File); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.File)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) string); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterParty provides a mock function with given fields: ctx, req
func (_m *PartyUseCases) RegisterParty(ctx context.Context, req *request.PartyRegisterRequest) (*response.PartyResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterParty")
	}

	var r0 *response.PartyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.PartyRegisterRequest) (*response.PartyResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.PartyRegisterRequest) *response.PartyResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PartyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.PartyRegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateParty provides a mock function with given fields: ctx, req
func (_m *PartyUseCases) UpdateParty(ctx context.Context, req *request.PartyUpdateRequest) (*response.PartyResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParty")
	}

	var r0 *response.PartyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.PartyUpdateRequest) (*response.PartyResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.PartyUpdateRequest) *response.PartyResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.PartyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.PartyUpdateRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPartyUseCases creates a new instance of PartyUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartyUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartyUseCases {
	mock := &PartyUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
