// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks_usecases

import (
	context "context"

	request "github.com/nocturna-ta/election/internal/usecases/request"
	mock "github.com/stretchr/testify/mock"

	response "github.com/nocturna-ta/election/internal/usecases/response"

	uuid "github.com/google/uuid"
)

// SupportingPartyUseCases is an autogenerated mock type for the SupportingPartyUseCases type
type SupportingPartyUseCases struct {
	mock.Mock
}

// AddSupportingParty provides a mock function with given fields: ctx, req
func (_m *SupportingPartyUseCases) AddSupportingParty(ctx context.Context, req *request.AddSupportingPartyRequest) (*response.SupportingPartyResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AddSupportingParty")
	}

	var r0 *response.SupportingPartyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.AddSupportingPartyRequest) (*response.SupportingPartyResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.AddSupportingPartyRequest) *response.SupportingPartyResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.SupportingPartyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.AddSupportingPartyRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSupportingPartiesByPairID provides a mock function with given fields: ctx, pairID
func (_m *SupportingPartyUseCases) GetSupportingPartiesByPairID(ctx context.Context, pairID uuid.UUID) (*response.SupportingPartiesResponse, error) {
	ret := _m.Called(ctx, pairID)

	if len(ret) == 0 {
		panic("no return value specified for GetSupportingPartiesByPairID")
	}

	var r0 *response.SupportingPartiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*response.SupportingPartiesResponse, error)); ok {
		return rf(ctx, pairID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *response.SupportingPartiesResponse); ok {
		r0 = rf(ctx, pairID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.SupportingPartiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, pairID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveSupportingParty provides a mock function with given fields: ctx, req
func (_m *SupportingPartyUseCases) RemoveSupportingParty(ctx context.Context, req *request.RemoveSupportingPartyRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSupportingParty")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.RemoveSupportingPartyRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSupportingPartyUseCases creates a new instance of SupportingPartyUseCases. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupportingPartyUseCases(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupportingPartyUseCases {
	mock := &SupportingPartyUseCases{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
