// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Ping to check health",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.jsonResponse"
                        }
                    }
                }
            }
        },
        "/v1/election/pairs": {
            "get": {
                "description": "Get All Election Pairs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Election",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorized User",
                        "name": "X-User-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Address",
                        "name": "X-Address-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Role",
                        "name": "X-Role",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.jsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ElectionPairListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/election/pairs/number/{no}": {
            "get": {
                "description": "Get Election Pair By Number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Election",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorized User",
                        "name": "X-User-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Address",
                        "name": "X-Address-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Role",
                        "name": "X-Role",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Election Number",
                        "name": "no",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.jsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ElectionPairResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/election/pairs/register": {
            "post": {
                "description": "Register Election Pair (President and Vice President)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Election",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorized User",
                        "name": "X-User-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Address",
                        "name": "X-Address-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Role",
                        "name": "X-Role",
                        "in": "header"
                    },
                    {
                        "description": "Registration Request",
                        "name": "pair",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.ElectionPairRegistrationRequest"
                        }
                    },
                    {
                        "type": "file",
                        "description": "Pair Photo (jpg, jpeg, png only)",
                        "name": "pair_photo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "President Photo (jpg, jpeg, png only)",
                        "name": "president_photo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Vice President Photo (jpg, jpeg, png only)",
                        "name": "vice_president_photo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.jsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ElectionPairResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/election/pairs/{id}": {
            "get": {
                "description": "Get Election Pair By ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Election",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorized User",
                        "name": "X-User-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Address",
                        "name": "X-Address-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Role",
                        "name": "X-Role",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Election Pair ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.jsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ElectionPairResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/election/pairs/{pairID}/detail": {
            "get": {
                "description": "Get Election Pair Detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Election"
                ],
                "summary": "Election Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorized User",
                        "name": "X-User-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Address",
                        "name": "X-Address-Id",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Authorized Role",
                        "name": "X-Role",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Election Pair ID",
                        "name": "pairID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.jsonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ElectionPairDetailResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.errorResponse": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "integer"
                },
                "error_message": {
                    "type": "string"
                }
            }
        },
        "controller.jsonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "error": {
                    "$ref": "#/definitions/controller.errorResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "request.ElectionPairRegistrationRequest": {
            "type": "object"
        },
        "response.CandidateInfoResponse": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "birth_place": {
                    "type": "string"
                },
                "education_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.EducationHistoryResponse"
                    }
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "job": {
                    "type": "string"
                },
                "last_education": {
                    "type": "string"
                },
                "photo_path": {
                    "type": "string"
                },
                "religion": {
                    "type": "string"
                },
                "work_experience": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.WorkHistoryResponse"
                    }
                }
            }
        },
        "response.EducationHistoryResponse": {
            "type": "object",
            "properties": {
                "institute_name": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "response.ElectionPairDetailResponse": {
            "type": "object",
            "properties": {
                "election_pair_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mission": {
                    "type": "string"
                },
                "program_docs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "vision": {
                    "type": "string"
                },
                "work_program": {
                    "type": "string"
                }
            }
        },
        "response.ElectionPairListResponse": {
            "type": "object",
            "properties": {
                "pairs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.ElectionPairResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.ElectionPairResponse": {
            "type": "object",
            "properties": {
                "election_no": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "pair_photo_path": {
                    "type": "string"
                },
                "president": {
                    "$ref": "#/definitions/response.CandidateInfoResponse"
                },
                "vice_president": {
                    "$ref": "#/definitions/response.CandidateInfoResponse"
                },
                "vote_count": {
                    "type": "integer"
                }
            }
        },
        "response.WorkHistoryResponse": {
            "type": "object",
            "properties": {
                "institute_name": {
                    "type": "string"
                },
                "position": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Election Service",
	Description:      "Election Management Service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
