basePath: /
definitions:
  controller.errorResponse:
    properties:
      error_code:
        type: integer
      error_message:
        type: string
    type: object
  controller.jsonResponse:
    properties:
      code:
        type: integer
      data: {}
      error:
        $ref: '#/definitions/controller.errorResponse'
      message:
        type: string
    type: object
  request.CandidateInfoRequest:
    properties:
      education_history:
        type: string
      full_name:
        type: string
      legal_record_history:
        type: string
      photo_path:
        type: string
      work_experience:
        type: string
    type: object
  request.ElectionPairRegistrationRequest:
    properties:
      election_no:
        type: string
      id:
        type: string
      pair_photo_path:
        type: string
      president:
        $ref: '#/definitions/request.CandidateInfoRequest'
      signed_transaction:
        type: string
      vice_president:
        $ref: '#/definitions/request.CandidateInfoRequest'
    type: object
  response.CandidateInfoResponse:
    properties:
      education_history:
        type: string
      full_name:
        type: string
      legal_record_history:
        type: string
      photo_path:
        type: string
      work_experience:
        type: string
    type: object
  response.ElectionPairDetailResponse:
    properties:
      election_pair_id:
        type: string
      id:
        type: string
      mission:
        type: string
      program_docs:
        items:
          type: string
        type: array
      vision:
        type: string
      work_program:
        type: string
    type: object
  response.ElectionPairListResponse:
    properties:
      pairs:
        items:
          $ref: '#/definitions/response.ElectionPairResponse'
        type: array
      total:
        type: integer
    type: object
  response.ElectionPairResponse:
    properties:
      election_no:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      pair_photo_path:
        type: string
      president:
        $ref: '#/definitions/response.CandidateInfoResponse'
      vice_president:
        $ref: '#/definitions/response.CandidateInfoResponse'
      vote_count:
        type: integer
    type: object
info:
  contact: {}
  description: Election Management Service.
  title: Election Service
  version: 1.0.0
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Ping to check health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.jsonResponse'
      summary: Ping
      tags:
      - Health
  /v1/election/pairs:
    get:
      consumes:
      - application/json
      description: Get All Election Pairs
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address-Id
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionPairListResponse'
              type: object
      summary: Election
      tags:
      - Election
  /v1/election/pairs/{id}:
    get:
      consumes:
      - application/json
      description: Get Election Pair By ID
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address-Id
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Election Pair ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionPairResponse'
              type: object
      summary: Election
      tags:
      - Election
  /v1/election/pairs/{pairID}/detail:
    get:
      consumes:
      - application/json
      description: Get Election Pair Detail
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address-Id
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Election Pair ID
        in: path
        name: pairID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionPairDetailResponse'
              type: object
      summary: Election Detail
      tags:
      - Election
  /v1/election/pairs/number/{no}:
    get:
      consumes:
      - application/json
      description: Get Election Pair By Number
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address-Id
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Election Number
        in: path
        name: "no"
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionPairResponse'
              type: object
      summary: Election
      tags:
      - Election
  /v1/election/pairs/register:
    post:
      consumes:
      - application/json
      description: Register Election Pair (President and Vice President)
      parameters:
      - description: Authorized User
        in: header
        name: X-User-Id
        type: string
      - description: Authorized Address
        in: header
        name: X-Address-Id
        type: string
      - description: Authorized Role
        in: header
        name: X-Role
        type: string
      - description: Registration Request
        in: body
        name: pair
        required: true
        schema:
          $ref: '#/definitions/request.ElectionPairRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.jsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElectionPairResponse'
              type: object
      summary: Election
      tags:
      - Election
swagger: "2.0"
